# Generated by Django 5.1.3 on 2024-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='ciudad_destino',
            field=models.CharField(default='Bogotá', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
